name: 'Massa Station install'

inputs:
  os:
    default: 'ubuntu-20.04'

runs:
  using: "composite"
  steps:
    - name: Set apt up Cache
      if: startsWith(inputs.os, 'ubuntu-')
      id: cache
      uses: actions/cache@v2
      with:
        path: /var/cache/apt/archives
        # increase cache version if new packages are added
        key: ${{ runner.os }}-apt-build-v1

    - name: installing linux dependencies
      if: steps.cache.outputs.cache-hit != 'true' && startsWith(inputs.os, 'ubuntu-')
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y libgl1-mesa-dev xorg-dev gcc-mingw-w64-x86-64 p7zip

    - uses: actions/setup-go@v3
      with:
        go-version: 1.19.2
        cache: true

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        cache-dependency-path: |
          web/home/package-lock.json
          web/plugin-manager/package-lock.json

    - name: install go deps
      shell: bash
      run: |
        go install github.com/go-swagger/go-swagger/cmd/swagger@latest
        go install golang.org/x/tools/cmd/stringer@latest

    - name: Build react frontend and swagger api
      shell: bash
      run: go generate ./...
